language: c

sudo: false

matrix:
  include:
    - env: CABALVER=1.18 GHCVER=7.6.3
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.6.3], sources: [hvr-ghc]}}
    - env: CABALVER=1.18 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.2
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2], sources: [hvr-ghc]}}

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - export BENCH_TARGET=7.10.1
  - openssl aes-256-cbc -K $encrypted_71d9d79f11c1_key -iv $encrypted_71d9d79f11c1_iv -in .continuous-benchmark.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

install:
  - bash ./.travis-install.sh

script: cabal configure --enable-tests && cabal build && cabal test

after_success:
  - bash ./.continuous-benchmark.sh
