language: haskell

env:
  - CABALVER=1.18 GHCVER=7.6.3
  - CABALVER=1.18 GHCVER=7.8.4
  - CABALVER=1.22 GHCVER=7.10.1

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

  - export BENCH_TARGET=7.10.1
  - openssl aes-256-cbc -K $encrypted_71d9d79f11c1_key -iv $encrypted_71d9d79f11c1_iv -in .continuous-benchmark.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

install:
  - bash ./.travis-install.sh

after_success:
  - bash ./.continuous-benchmark.sh
